version: '3.3'

services:

    keycloak:

        container_name: keycloak

        image: quay.io/keycloak/keycloak:20.0.2

        command:

            - 'start-dev'

        environment:

            - KEYCLOAK_ADMIN=admin

            - KEYCLOAK_ADMIN_PASSWORD=SENHA

            - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/cert/CERT.cer

            - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/cert/CERT.key

        volumes:

            - './cert:/opt/keycloak/cert/'

        ports:

            - 443:8443
